# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oNfg5YWFljEvUtgGEt7W56HVdxHtQtcU

# Master's Final Year Project

## 1) Imports
Import the libraries used throughout the notebook.
"""

import pandas as pd
import matplotlib.pyplot as plt

"""## 2) Configuration
Set file path, key columns, core indicators, and plot toggles.
"""

PATH = "/content/world_bank_data_2025.csv"

COUNTRY_COL = "country_name"
YEAR_COL = "year"

"""## 3) Load dataset + basic cleaning
Load the CSV, standardize country strings, coerce year to numeric, and print a quick overview.
"""

# Load
df = pd.read_csv(PATH)

# Basic column checks
required_cols = [COUNTRY_COL, YEAR_COL]
missing_required = [c for c in required_cols if c not in df.columns]
if missing_required:
    raise ValueError(f"Missing required columns: {missing_required}")

# Clean country
df[COUNTRY_COL] = df[COUNTRY_COL].astype(str).str.strip()

# Coerce year (drop rows where year is invalid/missing)
df[YEAR_COL] = pd.to_numeric(df[YEAR_COL], errors="coerce").astype("Int64")
df = df.dropna(subset=[YEAR_COL]).copy()

# Overview
print(f"Rows: {len(df):,}")
print(f"Columns: {df.shape[1]}")
print("First 20 columns:", list(df.columns[:20]))
if df.shape[1] > 20:
    print(f"... and {df.shape[1] - 20} more columns.")
print(f"Year coverage (all countries): {int(df[YEAR_COL].min())} -> {int(df[YEAR_COL].max())}")

AFRICAN_COUNTRIES = [
    "Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi","Cabo Verde",
    "Cameroon","Central African Republic","Chad","Comoros","Congo, Dem. Rep.",
    "Congo, Rep.","Cote d'Ivoire","Djibouti","Egypt, Arab Rep.","Equatorial Guinea",
    "Eritrea","Eswatini","Ethiopia","Gabon","Gambia, The","Ghana","Guinea",
    "Guinea-Bissau","Kenya","Lesotho","Liberia","Libya","Madagascar","Malawi",
    "Mali","Mauritania","Mauritius","Morocco","Mozambique","Namibia","Niger",
    "Nigeria","Rwanda","Sao Tome and Principe","Senegal","Seychelles",
    "Sierra Leone","Somalia","South Africa","South Sudan","Sudan","Tanzania",
    "Togo","Tunisia","Uganda","Zambia","Zimbabwe"
]
df_africa = df[df[country_col].isin(AFRICAN_COUNTRIES)].copy()

print("\nNumber of African countries:", df_africa[country_col].nunique())


# Detect key columns
country_col_candidates = ["country_name", "Country Name", "country", "Country"]
year_col_candidates = ["year", "Year"]

country_col = next((c for c in country_col_candidates if c in df.columns), None)
year_col = next((c for c in year_col_candidates if c in df.columns), None)

if country_col is None or year_col is None:
    raise ValueError("Country or Year column not found.")

"""- The dataset loaded correctly with **3,472 rows** and **16 columns**.
- The time span is **2010 to 2025**, which is a complete 16-year coverage and is suitable for short macro trend analysis.
- Key identifier columns are present (`country_name`, `country_id`, `year`).

## 5) Type consistency checks (lightweight)
We print dtypes, then for **object** columns we test how many values can be coerced to numeric. This helps detect columns that *should* be numeric but contain strings/symbols.
"""

print("Dtypes (as read from CSV):")
print(df.dtypes.astype(str))

# Numeric consistency on object columns (excluding country)
object_cols = [c for c in df.columns if df[c].dtype == "object" and c != COUNTRY_COL]

type_check_rows = []
for c in object_cols:
    s = df[c]
    non_missing = int(s.notna().sum())
    numeric = pd.to_numeric(s, errors="coerce")
    numeric_non_missing = int(numeric.notna().sum())
    non_numeric = non_missing - numeric_non_missing

    # keep only columns with at least some non-numeric issues (to reduce noise)
    if non_numeric > 0 and non_missing > 0:
        type_check_rows.append((c, str(s.dtype), non_missing, numeric_non_missing, non_numeric))

"""- Most columns are already stored as numeric types (`float64`), which means they can be used directly for calculations and plotting.
- Only the identifier fields (`country_name`, `country_id`) are `object`, which is expected and not a data quality issue.
- The numeric consistency check flagged only `country_id` as non-numeric, which is normal because it is an identifier code (not a quantitative variable).

## Identifying Usable Years

A data-quality check is performed before modelling. This helps separate:

* Years with stable data (usable)

* Years with incomplete data (excluded)
"""

# -----------------------------
# Filter African countries
# -----------------------------
df_africa = df[df[country_col].isin(AFRICAN_COUNTRIES)].copy()

# -----------------------------
# Use ALL indicators (exclude identifiers)
# -----------------------------
exclude_cols = {country_col, year_col, "country_id", "Country Code"}
indicator_cols = [c for c in df_africa.columns if c not in exclude_cols]

# -----------------------------
# Compute missing values per year
# -----------------------------
missing_per_year = df_africa.groupby(year_col)[indicator_cols].apply(lambda g: g.isna().sum().sum())
total_cells_per_year = df_africa.groupby(year_col)[indicator_cols].apply(lambda g: g.shape[0] * g.shape[1])

missing_percent_per_year = (missing_per_year / total_cells_per_year) * 100

# -----------------------------
# Plot (no colors specified)
# -----------------------------
plt.figure(figsize=(8,5))
plt.plot(missing_percent_per_year.index, missing_percent_per_year.values, marker='o')
plt.xlabel("Year")
plt.ylabel("Missing Values (%)")
plt.title("Missing Data Across Years (All Indicators, African Countries)")
plt.tight_layout()
plt.show()

"""* Missing values increase sharply in 2024 and are nearly complete in 2025.

* These years are **not usable** because many indicators have not yet been officially reported.

* This reflects **reporting delays and ongoing revisions** in international databases.

Therefore, the analysis is limited to 2010–2023, the most reliable period.

## Exploring Usable Indicators and Countries

* Countries are evaluated based on the completeness of these indicators.

* Only African countries with reliable and consistent observations are retained.
"""

# -----------------------------
# KEEP DATA ONLY UNTIL 2023
# -----------------------------
df = df[df[year_col] <= 2023].copy()

print("\nYears kept:", df[year_col].min(), "→", df[year_col].max())

# -----------------------------
# Intersting Indicators
# -----------------------------
INDICATORS = [
    "GDP Growth (% Annual)",
    "Inflation (CPI %)",
    "Unemployment Rate (%)",
    "GDP per Capita (Current USD)",
    "Current Account Balance (% GDP)",
    "Government Expense (% of GDP)",
    "Government Revenue (% of GDP)",
    "Tax Revenue (% of GDP)",
    "Public Debt (% of GDP)",
]

INDICATORS = [c for c in INDICATORS if c in df.columns]

print("\nIndicators used:")
print(INDICATORS)

print("\nNumber of African countries:", df_africa[country_col].nunique())

# -----------------------------
# Compute missing values
# -----------------------------
missing_counts = (
    df_africa
    .groupby(country_col)[INDICATORS]
    .apply(lambda g: g.isna().sum())
)

row_counts = df_africa.groupby(country_col).size()

missing_percent = missing_counts.div(row_counts, axis=0) * 100

# -----------------------------
# 7) DISPLAY RESULTS
# -----------------------------
print("\n==================")
print("MISSING VALUES (%)")
print("==================\n")
print(missing_percent.round(2).to_string())

"""* Financial indicators (e.g., government revenue, tax revenue, public debt, government expenditure) show very high levels of missing data across most countries.

* The missingness is structural, meaning these variables are **not consistently reported** rather than temporarily unavailable.

Including them would significantly reduce the sample size and introduce bias.
Therefore, **these indicators are excluded from the analysis.**

## Selected Indicators

The analysis focuses on core macroeconomic variables that are consistently reported and directly related to short-term economic dynamics:

* GDP Growth (% Annual): measures economic performance (target variable).

* Inflation (CPI %): captures price dynamics and macroeconomic pressure.

* Unemployment Rate (%): reflects labour market conditions and internal slack.

* GDP per Capita (Current USD): proxy for income level and structural development.

* Current Account Balance (% GDP): indicates external exposure and dependence on trade and commodities.

These indicators provide sufficient information to analyse economic vulnerability without relying on incomplete fiscal data.

## Selected Countries

After excluding countries with structurally missing or unreliable data, the study retains the following 12 African countries:

* Algeria

* Morocco

* Tunisia

* Egypt

* South Africa

* Kenya

* Ghana

* Tanzania

* Senegal

* Côte d'Ivoire

* Botswana

* Zambia


These countries were selected because they:

* Have sufficiently complete data over 2010–2023,

* Represent diverse but comparable economic structures,

* Include both resource-dependent and more diversified economies,

* Provide a balanced panel suitable for statistical learning and comparison.
"""

CORE_INDICATORS = [
    "GDP Growth (% Annual)",
    "Inflation (CPI %)",
    "Unemployment Rate (%)",
    "GDP per Capita (Current USD)",
    "Current Account Balance (% GDP)",
]
print("\nSelected indicators:", CORE_INDICATORS)

SELECTED_COUNTRIES = [
    "Algeria","Morocco","Tunisia","Egypt, Arab Rep.",
    "South Africa","Kenya","Ghana","Tanzania",
    "Senegal","Cote d'Ivoire","Botswana","Zambia"
]
print("\nSelected countries:", SELECTED_COUNTRIES)

# -----------------------------
# Build a clean dataset for the 12 selected countries
# -----------------------------
panel_core = (
    df[[COUNTRY_COL, YEAR_COL] + CORE_INDICATORS]
    .sort_values([COUNTRY_COL, YEAR_COL])
    .copy()
)

# -----------------------------
# Loop over indicators → 1 plot per indicator
# -----------------------------
for indicator in CORE_INDICATORS:

    plt.figure(figsize=(9, 4))

    # For each country draw one line
    for country in SELECTED_COUNTRIES:

        country_df = (
            panel_core[panel_core[COUNTRY_COL] == country]
            [[YEAR_COL, indicator]]
            .dropna()                      # drop NA only for this indicator
            .sort_values(YEAR_COL)
        )

        if country_df.empty:
            continue

        plt.plot(
            country_df[YEAR_COL].astype(int),
            country_df[indicator],
            marker="o",
            label=country
        )

    plt.title(f"{indicator} — 12 Country Comparison")
    plt.xlabel("Year")
    plt.ylabel(indicator)
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=8, ncol=3)
    plt.tight_layout()
    plt.show()